[package]
authors = ["Tim McNamara <tim@mcnamara.nz>"]
edition = "2021"
name = "hello_actix"
version = "0.1.0"

[dependencies]
actix-web = "4"
actix-web-httpauth = "0.8"
fastrand = "2.1.1"
base64 = "0.22"
ring = "0.17"
serde = { version = "1.0.204", features = ["derive"] }
