[target.x86_64-unknown-linux-musl]
rustflags = [
  "-C",
  "target-feature=+crt-static",
  "-C",
  "linker=rust-lld",
]

[target.aarch64-unknown-linux-musl]
rustflags = [
  "-C",
  "target-feature=+crt-static",
  "-C",
  "linker=rust-lld",
]

[build]
# uncomment for x86
# target = ["x86_64-unknown-linux-musl"]

# uncomment for ARM
# target = ["aarch64-unknown-linux-musl"]

# or build both..
# target = ["x86_64-unknown-linux-musl", "aarch64-unknown-linux-musl"]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]
